Season.create(name: "2015")
Season.create(name: "2015-2016")
Season.create(name: "2016")
Season.create(name: "2016-2017")
Season.create(name: "2017")
Season.create(name: "2017-2018")
Season.create(name: "2018")
Season.create(name: "2018-2019")
s2019 = Season.create(name: "2019")
Season.create(name: "2019-2020")
Season.create(name: "2020")
Season.create(name: "2020-2021")

bbll = Sport.create(name: "Baseball", gender: "Men's")
bb = Sport.create(name: "Basketball", gender: "Men's")
fb = Sport.create(name: "Football", gender: "Men's")
g = Sport.create(name: "Golf", gender: "Men's")
l = Sport.create(name: "Lacrosse", gender: "Men's")
s = Sport.create(name: "Soccer", gender: "Men's")
t = Sport.create(name: "Tennis", gender: "Men's")
tf = Sport.create(name: "Track & Field", gender: "Men's")
w = Sport.create(name: "Wrestling", gender: "Men's")
bbw = Sport.create(name: "Basketball", gender: "Women's")
fh = Sport.create(name: "Field Hockey", gender: "Women's")
gw = Sport.create(name: "Golf", gender: "Women's")
lw = Sport.create(name: "Lacrosse", gender: "Women's")
r = Sport.create(name: "Rowing", gender: "Women's")
sw = Sport.create(name: "Soccer", gender: "Women's")
sb = Sport.create(name: "Softball", gender: "Women's")
tw = Sport.create(name: "Tennis", gender: "Women's")
tfw = Sport.create(name: "Track & Field", gender: "Women's")
v = Sport.create(name: "Volleyball", gender: "Women's")

baseball2019 = Team.create(sport_id: bbll.id, season_id: s2019.id)

Athlete.create(team: baseball2019, firstname: "Aaron", lastname: "Sabato", number: "19", year: "Jr", height: "6-2", weight: 230, city: "Rye Brook", state: "NY", high_school: "Brunswick School", ig_handle: "@aaron_sabato14", biography: "He was born as a child...")
Athlete.create(team_id: 2, firstname: "Garrison", lastname: "Brooks", number: "15", year: "Sr", height: "6-9", weight: 235, city: "Lafayette", state: "AL", high_school: "Auburn", ig_handle: "@garrison_brooks", biography: "It all started in the beginning...")
Athlete.create(team_id: 15, firstname: "Brianna", lastname: "Pinto", number: "8", year: "So", height: "5-5", weight: 125, city: "Durham", state: "NC", high_school: "Jordan", ig_handle: "@b.pinto", biography: "And then she learned soccer")
Athlete.create(team_id: 3, firstname: "Dyami", lastname: "Brown", number: "2", year: "Jr", height: "6-0", weight: 195, city: "Charlotte", state: "NC", high_school: "West Mecklenberg", ig_handle: "@@_dyamibrown", biography: "Charlotte is home...")
Athlete.create(team_id: 19, firstname: "Destiny", lastname: "Cox", number: "1", year: "Jr", height: "6-1", weight: 150, city: "Carrboro", state: "NC", high_school: "Chapel Hill", ig_handle: "@destinycox", biography: "Her mom was fast...")
Athlete.create(team_id: 2, firstname: "Armando", lastname: "Bacot", number: "5", year: "So", height: "6-10", weight: 232, city: "Richmond", state: "VA", high_school: "IMG Academy", ig_handle: "@armando", biography: "VA then FL now NC")

User.create(name: "Mark C", email: "noneed@forthis.com", password: "password")
User.create(name: "Chris Cuomo", email: "chrisc@example.com", password: "password")
User.create(name: "Andrew Cuomo", email: "andrewc@example.com", password: "password")
